---
title: "resume"
author: Kyle Tolliver
output: 
  pagedown::html_resume:
    css: ['resume.css', resume]
    self_contained: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(results='asis', echo = TRUE)

library(tidyverse)
```

Aside
====================================

Contact Info {#contact}
------------------------------------

- <i class="fa fa-envelope"></i> [kyle@tollivers.org](mailto:kyle@tollivers.org?subject=Job)

- <i class="fa fa-phone"></i> [(805)367-6723](tel: 18053676723)

- <i class="fas fa-map-marker-alt"></i> [Highland, Utah, USA](https://www.google.com/maps/place/Highland,+UT/@40.4327126,-111.8226669,13)

- <i class="fa fa-linkedin"></i> [linkedin.com/in/kctolli/](https://www.linkedin.com/in/kctolli/)

- <i class="fa fa-link"></i> [kctolli.github.io](../../index.html)

Skills {#skills}
------------------------------------

- Python
- C / C++
- R / Rmd 
- Verilog
- Java
- SQL
- HTML 
- CSS
- Tableau
- Github

Disclaimer {#disclaimer}
------------------------------------

Member of [Tau Beta Pi](tbp.org) <br /> Engineering Honor Society <br /> Idaho Delta chapter at BYU-Idaho.

This resume was made with <br /> the R package [pagedown](https://github.com/rstudio/pagedown).

Main
====================================

Kyle Tolliver {#title}
------------------------------------

Education {data-icon=graduation-cap}
------------------------------------

### Brigham Young University - Idaho

Bachelor of Science in Software Engineering 

Rexburg, ID

2017 <br> | <br> 2020

+ Minor: Computer Engineering and Data Science
+ Coursework: Advanced Embedded Systems, Digital System Design, Computer Architecture, Machine Learning, Intermediate Stats, Data Intuition, Data Wrangling, Database Development, Software Development, Web Development, System Security, Project Management, Linear Algebra, Discrete Math, Differential Calculus  

Experience {data-icon=briefcase}
------------------------------------

### Assistant Project Manager

RBDC - Research and Business Development Center

Remote

2020

+ Used Python to create functions and Machine Learning algorithms
+ Developed code in shortest path optimization for warehouse robot
+ Lead Scrum meetings and helped programmers develop code

### Research Specialist Intern

LLNL - Lawrence Livermore National Labs

Remote

2020

+ Tested security technologies using binary analysis
+ Conducted market research on new security techniques
+ Followed Scrum methodology and Kanban (Trello) board  

### Student Senior Designer

NASA - National Aeronautics and Space Administration

Remote

2020

+ Developed embedded C interface to the sensors in NASA's Spacesuit 
+ Benchmark tested the microprocessor in C++
+ Setup a website using Rmds, CSS and Yaml

Projects {data-icon=laptop}
------------------------------------

### Spotify Predictive Analytics 		

BYU - Idaho, Computer Science and Engineering 

Rexburg, ID

2020 

+ Used energy, liveliness, length and tempo to predict song popularity
+ Created Regression models in R
+ Developed Neural Networks and Decision Trees using Python

### COVID-19 Data Consulting

BYU - Idaho, Computer Science and Engineering 

Remote

2020

+ Developed a data website using R, Rmds and Yaml
+ Explored different datasets to determine viable information
+ Wrote my own COVID-19 R package to wrangle data
+ Visualized the data to make the data easily understood

### Self Driving Car	

BYU - Idaho, Computer Science and Engineering 

Rexburg, ID

2020 

+ Designed circuits and assembled the electronics
+	Programmed the Arduino in Embedded C
+	Setup Raspberry Pi for Deep Learning and Computer Vision