---
title: "Cover Letter"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Dear Hiring Manager,

I am seeking the _______ position with ________.

My resume illustrates my programming and hardware experience. I am not afraid to ask for help or clarification when I need it. I also know how to find answers to any questions from study. I will spend my own outside of work to learn needed material for this position. I am a creative thinker with an ever-present thirst to solve complex problems such as discrete math problems. I am confident that with my technical experience I would make an immediate contribution to ___________.

The following are just a few of the highlights of my qualifications:
*	Received recognition for my dedication to engineering and learning by joining Tau Beta Pi 
*	Solid understanding of how hardware and software interact
*	I also will put work as my top priority 
* Data Science and Analytics skills

My experience in developing software with a time constraint will allow me to a great asset to your company. 

I can be reached at (805)367-6723 or kyle@tollivers.org. Thank you for your consideration. I look forward to speaking with you.

Sincerely,
Kyle Tolliver

