---
title: "resume"
author: Kyle Tolliver
output: pagedown::html_resume
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Aside
====================================

Contact Info {#contact}
------------------------------------

- <i class="fa fa-envelope"></i> kyle@tollivers.org

- <i class="fa fa-phone"></i> [(805)367-6723](tel: 18053676723)

- <i class="fa fa-linkedin"></i> [kctolli](https://www.linkedin.com/in/kctolli/)

- <i class="fas fa-globe-americas"></i> https://kctolli.github.io/

- <i class="fa fa-github"></i> https://github.com/kctolli

Skills {#skills}
------------------------------------

- R 
- YAML
- Python
- C/C++
- Tableau
- Excel
- SQL
- HTML 
- CSS
- Java
- Verilog
- Embedded C
- Assembly
- Github

Disclaimer {#disclaimer}
------------------------------------

This resume was made with <br /> the R package [pagedown](https://github.com/rstudio/pagedown).

Last updated on `r Sys.Date()`.

Kyle Tolliver --- Resume


Main
====================================

Kyle Tolliver {#title}
------------------------------------

Education {data-icon=graduation-cap}
------------------------------------

### Brigham Young University-Idaho

Bachelor of Science in Software Engineering

Rexburg, ID

2017 <br> | <br> 2020

+ Minor: Computer Engineering
+ Honors: Tau Beta Pi and LDS Academic Scholarship
+ Coursework: Data Structures, Software Design and Development, Web Development, System Security, Digital Systems Design, Computer Architecture, Advanced Embedded Systems, Circuit Theory and Analysis

### Brigham Young University-Idaho

Associate of Applied Science in Data Science

Rexburg, ID

2017 <br> | <br> 2020

+ Societies: Data Science Society
+ Coursework: Database Development, Data Intuition and Insight, Data Wrangling, Programming with Classes, Technical Communication, Project Management, Linear Algebra, Discrete Math, Calculus 1 

Experience {data-icon=briefcase}
------------------------------------

### Student Senior Design Project

NASA - National Aeronautics and Space Administration

Remote

2020

+ Was contracted by NASA for my [Senior Project](https://ecen499-nasa.github.io/)
+ Used embedded C to interface with sensors to monitor human vitals while in space
+ Using C++ to benchmark test the CPU
+ Setup the webpage using Rmds, CSS and Yaml

### Teaching Assistant and Tutor

BYU - Idaho, Computer Science and Engineering 

Rexburg, ID

2018  <br> | <br>  2020

+ Lead students to increase their knowledge
+ Guide students to improvement by giving feedback
+ Help students with programming Verilog, Embedded C and Erlang

Projects {data-icon=laptop}
------------------------------------

### Exam Data Analysis

BYU - Idaho, Biology

Rexburg, ID

2020

+ Used R and the Tidyverse package to wrangle and visualize data
+ Allowed Professors to help improve curriculum

### Self Driving Car

BYU - Idaho, Computer Science and Engineering 

Rexburg, ID

2020

+ Designed Circuits and Assembled the Electronics
+ Programmed the Arduino in Embedded C
+ Setup Raspberry Pi for Deep Learning and Computer Vision

<!-- ### FPGA Multifunction Calculator -->

<!-- BYU - Idaho, Computer Science and Engineering -->

<!-- Rexburg, ID -->

<!-- 2019 -->

<!-- + Created new AVR commands -->
<!-- + Used Basys 3 (Artix 7) FPGA Board and developed in Verilog code -->

<!-- ### Calendaring App -->

<!-- BYU - Idaho, Computer Science and Engineering  -->

<!-- Rexburg, ID -->

<!-- 2018 -->

<!-- + Used Github to develop the Java code while working with a Team -->
<!-- + Presented to the Eastern Idaho Innovator’s Challenge -->

