---
title: "Kyle Tolliver"
editor_options: 
  chunk_output_type: console
---

```{r load_libraries, include=FALSE}
source("./site_libs/site.R")
load_libraries()
file <- "index"
```

```{r eval=FALSE}
render_web()
```

<!-- <body onload=`r alert('This website is setup as a personal portfolio.')`> -->

```{r start}
print_portfolio()
nav()
print_pic("./site_libs/images/me.jpg")
print_newline()
print_h2("About Me")
pander("BYU-Idaho graduate with a Bachelor's (BS) in Software Engineering. 
       I also earned a minor in Computer Engineering and Data Science. 
       I love to learn new things and solve problems.\n\n")
```

<div `r px0()`><span class="tooltipr"><a href="javascript:showhide('me')">A little more about me</a></span><div id="me" `r px20()`>

```{r about}
print_newline()
print_h4("Societies")
print_soc()
print_newline()
print_h4("Top Skills")
print_skills()
```

</div></div><br />

```{r main}
print_newline()
print_h2("Contact Me")
print_contact(file)
pagebreak()
print_newline()
print_h2("Highlights")
print_highlights() 
print_newline()
footer(file)
```

<!-- </body> -->