---
title: "Program of Study"
---

```{r load, include=FALSE}
library(mosaic)
library(tidyverse)
library(pander)
library(DT) 
library(knitr)

grade <- read_csv("./site_libs/records/grade.csv") %>% na.omit()
```

<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
</script>

<style>

</style>

## Brigham Young University - Idaho

*2020 Graduate*

I earned a Bachelor's of Science in Software Engineering with a minor in Computer Engineering and Data Science.

<!-- <div style="padding-left:5px;"> -->

<!-- <span class="tooltipr"> -->
<!-- <a href="javascript:showhide('hovertobegin')"><p style="color:blue;">Grades</p></a> -->
<!--   <span class="tooltipRtext">My cumulative GPA is <br/> 3.64 out of 4 </span> -->
<!-- </span> -->
<!-- <div id="hovertobegin" style="display:none;padding-left:20px;"> -->

<!-- ```{r display, echo=FALSE} -->
<!-- pander(grade, caption = "Applicable Coursework - Grades") -->
<!-- ``` -->

<!-- </div> -->
<!-- </div> -->

### Software Engineering (BS)

* Intro to Software Development using C++
* Object-Oriented Development using C++
* Software Design and Development using Java
* Introduction to Programming for IT
* System Security 
* Senior Practicum 
* Senior Project 

### Data Science Minor

* Database Design and Development
* Data Intuition and Insight
* Data Wrangling and Visualization
* Machine Learning and Data Mining

### Computer Engineering Minor

* Electric Circuit Analysis 
* Electronic Devices and Circuits
* Microprocessor Based-System Design
* Digital System Design
* Computer Architecture
* Embedded Systems
* Advanced Embedded Systems

### Core {.tabset .tabset-fade}

#### Math and Science

* PreCalculus
* Differential Calculus
* Linear Algebra 
* Discrete Math 
* Intermediate Statistics
* Introduction to Chemistry
* Foundations of Science

#### Programming

* Intro to Computer Science and Engineering
* Intro to Programming using Python
* Object-Oriented Programming with Data Structures using Python
* Introduction to Databases using SQL
* Fundamentals of Digital Systems with Lab
* Web Design and Development
* Project Management

#### General

* Family and Human Relations
* Introduction to the Visual Arts and Design
* Writing and Reasoning
* Technical Communication

###
<hr/>

## Moorpark High School

*2017 Graduate*

I was able to take some college level courses in the process of getting my High School Diploma. <br/> Moorpark High School graduating class of 2017.  

* Geometry Honors
* Algebra 2 Accelerated 
* PreCalculus Honors
* AP Calculus
* AP Chemistry
* AP Physics 1 & 2
* AP Art 2-D Design (Photography)
* Introduction to Computer Science using C++
* Introduction to Engineering
