---
title: "Projects"
---
<!--
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
-->

```{r load_libraries, include=FALSE}
knitr::opts_chunk$set(results = 'asis', echo = FALSE, message = FALSE, warning = FALSE)
pacman::p_load(tidyverse, glue)

source("./site_libs/script.R")
datapath <- "./site_libs/data/"
```

```{r eval=FALSE}
setwd(glue("{here}kctolli.github.io/"))
render_all()
```

<script src="./site_libs/script.js"></script>

```{r}
entries <- read_csv(glue("{datapath}entries.csv"))
print_project(entries)
```

<hr />

<footer><div style="padding-left:0px;">

<span class="tooltipr"><a href="javascript:showhide('copyright')"><p style="color:blue;">`r copyright()`</p></a></span>
<div id="copyright" style="display:none;padding-left:20px;">

```{r license}
gnu <- read_csv(glue("{datapath}license.csv"))
glue_data(gnu, "###### --- {details} \n")
```

</div></div></footer>