---
title: "Skills"
---

<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
</script>

<style>
a {color: blue;}
p {color: black;}
.tooltipRtext {color: white;}
ul {text-align: left; color: black;}
</style>

## Computer Engineering

### Embedded Systems {.tabset .tabset-fade}

#### Tools

##### Programming

<ul>

<div style="padding-left:0px;">
<span class="tooltipr"><a href="javascript:showhide('C')"><li style="color:gray;">C/C++ </li></a>
<span class="tooltipRtext"><ul style="color:white;">
<li>Embedded</li>
<li>Register-level</li>
</ul></span></span></div>

<li>Python</li>
<li>Assembly</li>
<li>Machine Code</li>
<li>Simulink</li>

</ul>

##### Embedded OS

<ul>

<li>ROS (Robot Operating System)</li>
<li>VxWorks</li>
<li>FreeRTOS</li>
<li>Windows IOT</li>

<div style="padding-left:0px;">
<span class="tooltipr"><a href="javascript:showhide('linux')"><li style="color:gray;">Linux</li></a>
<span class="tooltipRtext"><ul style="color:white;">
<li>Real-Time</li>
<li>Embedded</li>
<li>Raspberry OS</li>
</ul></span></span></div>
</ul>

#### Resources

##### Environments
  
* Code Composer Studio
* SoftConsole
* MATLAB
* Energia
* Arduino IDE
  
##### Microcontrollers

* Intel Galileo
* Raspberry Pi
* LattePanda
* ESP 8266
* MSP 432
* Arduino
    
##### Internet of Things

* Communications
* Information
* Fourier Series and Transform
* Filters
* Networking    
    
### Digital Systems {.tabset .tabset-fade}

#### FPGAs and HDLs

<ul>

<div style="padding-left:0px;">
<span class="tooltipr"><a href="javascript:showhide('verilog')"><li style="color:gray;">Verilog</li></a>
<span class="tooltipRtext">Developed using: Vivado <br/> on a Artix 7 and Kintex 7</span></span></div>
<ul>
<li>Behavioral</li> 
<li>Dataflow</li>
<li>Structural</li>
<li>System</li>
</ul>

<div style="padding-left:0px;">
<span class="tooltipr"><a href="javascript:showhide('vhdl')"><li style="color:gray;">VHDL</li></a>
<span class="tooltipRtext">Developed using: Libero <br/> on a PolarFire</span></span></div>
</ul>
  
#### Simulation and Testing

<ul>

<li>Verilog Test Bench</li>
<li>Logisim</li>
<li>Waveform</li>

<div style="padding-left:0px;">
<span class="tooltipr"><a href="javascript:showhide('IC')"><li style="color:gray;">Logic Integrated Circuits</li></a>
<span class="tooltipRtext"><ul style="color:white;">
<li>TTL (7400-Series)</li>
<li>CMOS</li>
</ul></span></span></div>
</ul>

### Computer Systems

* Computer Organization
* Memory Hierarchy 
* Computer Arithmetic
* Processor Design
* Pipelining
* Program Optimization
* Concurrency
* Parallelism
* Instruction Architecture
* Control Unit Design

### Circuit Analysis

<ul>

<div style="padding-left:0px;">
<span class="tooltipr"><a href="javascript:showhide('spice')"><li style="color:gray;">Spice Software</li></a>
<span class="tooltipRtext"><ul style="color:white;">
<li>LTSpice</li> 
<li>EasyEDA</li>
</ul></span></span></div>

<div style="padding-left:0px;">
<span class="tooltipr"><a href="javascript:showhide('op')"><li style="color:gray;">Transistors, Diodes, and Op-Amps</li></a>
<span class="tooltipRtext"><ul style="color:white;">
<li>MOSFETS</li> 
<li>BJT</li>
</ul></span></span></div>

<div style="padding-left:0px;">
<span class="tooltipr"><a href="javascript:showhide('BC')"><li>Basic Circuits</li></a>
<span class="tooltipRtext"><ul style="color:white;">
<li>Inductors</li> 
<li>Capacitors</li>
<li>Resistors</li>
</ul></span></span>
<div id="BC" style="display:none;padding-left:20px;">
<p>Methods and Techniques:</p>
<ul>
<li>Nodal</li> 
<li>Mesh</li>
<li>Kirchhoff's Laws</li> 
<li>Thevenin's Theorem</li> 
<li>Norton's Theorem</li>
</ul></div></div></ul>

## Data Science

### Tools

<ul>

<div style="padding-left:0px;">
<span class="tooltipr"><a href="javascript:showhide('R')"><li>R</li></a>
<span class="tooltipRtext">Developed using: RStudio <br/> with Rmd files and R Scripts</span>
</span>
<div id="R" style="display:none;padding-left:20px;">

Packages include: 

<ul>

<div style="padding-left:1px;">
<span class="tooltipr"><a href="javascript:showhide('tidy')"><li style="color:gray;">tidyverse</li></a>
<span class="tooltipRtext" style="color:white;"><ul style="color:white;">
<li>ggplot2</li> 
<li>dplyr</li>
<li>tidyr</li>
<li>readr</li>
<li>purr</li> 
<li>tibble</li>
<li>stringr</li>
<li>forcats</li></li>
</ul></span></span></div>

<li>knitr</li>
<li>stringi</li>
<li>reticulate</li>
<li>lubridate</li>
<li>dygraphs</li>
<li>sf (simple features)</li>
<li>leaflet</li>
<li>devtools</li>
<li>downloader</li>
<li>pagedown</li>
<li>pacman</li>
<li>installer</li>
<li>blogdown</li>
<li>mosaic</li>
<li>car</li>
</ul></div></div>
  
<div style="padding-left:0px;">
<span class="tooltipr"><a href="javascript:showhide('Py')"><li>Python</li></a>
<span class="tooltipRtext">Developed using: <br/> Google Colab <br/> with Jupyter Notebooks</span>
</span>
<div id="Py" style="display:none;padding-left:20px;">

Libraries include:

  + Pandas
  + Matplotlib
  + Numpy
  + Plotly
  + Math
  + Tensor Flow
  + SciPy
  + Random
</div></div>  
  
<li>Tableau</li>

<li>Databases

<ul>
<div style="padding-left:0px;">
<span class="tooltipr"><a href="javascript:showhide('spread')"><li style="color:gray;">Spreadsheets</li></a>
<span class="tooltipRtext"><ul style="color:white;">
<li>Excel</li> 
<li>Google Sheets</li>
<li>LibreOffice Calc</li>
<li>R Data Editor</li>
</ul></span></span></div>

<div style="padding-left:0px;">
<span class="tooltipr"><a href="javascript:showhide('sql')"><li style="color:gray;">SQL</li></a>
<span class="tooltipRtext"><ul style="color:white;">
<li>Oracle</li> 
<li>MySQL</li>
</ul></span></span></div>

<div style="padding-left:0px;">
<span class="tooltipr"><a href="javascript:showhide('sql')"><li style="color:gray;">NoSQL</li></a>
<span class="tooltipRtext"><ul style="color:white;">
<li>MongoDB</li> 
</ul></span></span></div>
</li></ul>

### Statistics {.tabset .tabset-fade}

#### Tests

* t-test
* Wilcox
* ANOVA
* Kruskal-Wallis
* Regression
  + Linear
  + Logistic
* Chi-Squared 
  + Independence
  + Goodness of Fit
* Permutation and Randomization

#### Topics

* Distributions
* Z Scores
* P Values
* Experimental Design
* Probability Theory
* Confidence Intervals
* Hypothesis Testing
* Data Management
  + Intuition
  + Insight 
  + Wrangling 
  + Visualization
  + Exploration
  + Consulting
  + Mining
  
### Machine Learning

<div style="padding-left:0px;">
<span class="tooltipr"><a href="javascript:showhide('ML')"><div style="color:gray;">Algorithms include:</div></a>
<span class="tooltipRtext">Developed using Python</span>
</span></div>

* Classifiers
* Clustering
* Decision Trees
* K-Nearest Neighbors
* Neural Networks

## Information Technology

### Web Development

<ul>

<li>HTML</li>
<li>CSS</li>

<div style="padding-left:0px;">
<span class="tooltipr"><a href="javascript:showhide('JS')"><li style="color:gray;">JavaScript</li></a>
<span class="tooltipRtext">W3 Schools Quiz: 21/25</span>
</span></div>

<div style="padding-left:0px;">
<span class="tooltipr"><a href="javascript:showhide('CS')"><li style="color:gray;">C#</li></a>
<span class="tooltipRtext">W3 Schools Quiz: 23/25</span>
</span></div>

<!-- <div style="padding-left:1px;"> -->
<!-- <span class="tooltipr"><a href="javascript:showhide('php')"><li style="color:gray;">PHP</li></a> -->
<!-- <span class="tooltipRtext">W3 Schools Quiz: 22/25</span> -->
<!-- </span></div> -->

<div style="padding-left:0px;">
<span class="tooltipr"><a href="javascript:showhide('Rweb')"><li>R-based webpages</li></a></span>
<div id="Rweb" style="display:none;padding-left:20px;">

* Basic knitr    
  Basic building blocks:
  - knitr (R package)
  - _site.yml
  - index.Rmd
* Blogdown    
  Basic building blocks:
  - blogdown (R package)
  - config.toml
  - index.Rmd
<!-- * Bookdown     -->
<!--   Basic building blocks: -->
<!--   - bookdown (R package) -->
<!--   - config.toml -->
<!--   - index.Rmd   -->
* Pagedown    
  Basic building blocks:
  - pagedown (R package and templates)
  - knitr (R package)
  - Rmarkdown

</div></div></ul>  

### Operating Systems

<ul>

<div style="padding-left:0px;">
<span class="tooltipr"><a href="javascript:showhide('JS')"><li style="color:gray;">Linux</li></a>
<span class="tooltipRtext"><ul style="color:white;">
<li>Ubuntu</li>
<li>Fedora</li>
<li>Crouton</li>
<li>Debian</li>
</ul></span></span></div>

<li>Chrome OS</li>

<li>Microsoft Windows</li>
<ul>
<li>Office 365</li>
<li>Active Directory</li>
</ul>

<li>Virtual Machines</li>
<ul>
<li>VirtualBox</li>
<li>VMware</li>
</ul>

<li>Command lines</li>
<ul>
<li>Bash</li>
<li>Batch</li>
<!-- <li>Powershell</li> -->
<li>Windows Task Scheduler</li>
</ul>

</ul>  

### Security  

* Malware and Antimalware
* Social Engineering
* Cryptography
* Data and Networks 
* Authentication and Access
* Application and Device
* Business Continuity
* Risk Mitigation
* Binary Analysis

### Cloud Computing

* Git
  + Github
  + Bash
* Google Cloud
  + Drive
  + Colab
* Docker
* Kubernetes
* Network Computing
  + Virtual Network Computing (VNC)
  + Secure Shell (SSH)
  + Remote Desktop Protocol (RDP)
  
### Project Management

<ul>

<li>Technical Teamwork</li>
<li>Risk Management</li>

<div style="padding-left:0px;">
<span class="tooltipr"><a href="javascript:showhide('method')"><li style="color:gray;">Methodologies</li></a>
<span class="tooltipRtext"><ul style="color:white;">
<li>Agile</li>
<li>Scrum</li>
<li>Waterfall</li>
</ul></span></span></div>

<div style="padding-left:0px;">
<span class="tooltipr"><a href="javascript:showhide('kanban')"><li style="color:gray;">Kanban Board</li></a>
<span class="tooltipRtext"><ul style="color:white;">
<li>Trello</li>
<li>Jira</li>
</ul></span></span></div></ul> 

### General CIT

* Networking
* DevOps
* System Administration 
* Databases
  + Development 
  + Programming
  + Administration

## Mathematics

<ul>

<li>Differential Calculus</li>
<li>Linear Algebra</li>
<li>College Algebra</li>
<li>Trigonometry</li>

<div style="padding-left:0px;">
<span class="tooltipr"><a href="javascript:showhide('ba')"><li>Boolean Algebra</li></a></span>
<div id="ba" style="display:none;padding-left:20px;">

Topics include:

* Numbers Systems
* Signed Numbers
  + Signed Magnitude
  + 1's Complement
  + 2's Complement
* Theorems and Identities
  + Simplification
  + Consensus
  + DeMorgan's Rules
  + Sum of Products and Product of Sums
  + Canonical Forms
  + Minimization
  + Karnaugh Maps

</div></div>

<div style="padding-left:0px;">
<span class="tooltipr"><a href="javascript:showhide('dm')"><li>Discrete Math</li></a></span>
<div id="dm" style="display:none;padding-left:20px;">

Topics include:

* Sets and Logic
* Functions and Relations
* Combinatorics and Probability
* Number Theory and Practice
* Trees and Graphs
* Languages and Grammars

</div></div>

<div style="padding-left:0px;">
<span class="tooltipr"><a href="javascript:showhide('math')"><li style="color:gray;">Basic Math and Arithmetic</li></a>
<span class="tooltipRtext">W3 Schools Quiz: 25/25</span>
</span></div></ul>  

### Functional Programming
    
* MATLAB
* Mathematica
* Elisp
* Erlang

## General Programming

### Languages

<ul>

<div style="padding-left:0px;">
<span class="tooltipr"><a href="javascript:showhide('C++')"><li>C/C++</li></a>
<span class="tooltipRtext">W3 Schools Quiz: 25/25</span>
</span>
<div id="C++" style="display:none;padding-left:20px;">

Developed Using

* Visual Studio

</div></div>

<div style="padding-left:0px;">
<span class="tooltipr"><a href="javascript:showhide('Java')"><li>Java</li></a>
<span class="tooltipRtext">W3 Schools Quiz: 22/25</span>
</span>
<div id="Java" style="display:none;padding-left:20px;">

Developed Using

* IntelliJ
* Android Studio

</div></div>

<div style="padding-left:0px;">
<span class="tooltipr"><a href="javascript:showhide('Python')"><li>Python</li></a>
<span class="tooltipRtext">W3 Schools Quiz: 25/25</span>
</span>
<div id="Python" style="display:none;padding-left:20px;">

Developed Using

* PyCharm 
* Thony
* Jupyter Notebook

</div></div></ul>  

### Design Patterns

* Multithreading
* UML Diagrams
* Model–view–controller
* Test Driven Development
* Observer
* Factory
* Singleton
* Adapter
* Template
* Composite

### Data Structures

* Arrays
* Stacks
* Heaps
* Queues
* Graphs
* Trees
* Linked Lists
* Hash Tables

## Industry Knowledge

### Interpersonal Skills

* Technical Communication
* Human Relations
* Problem Solving
* Teaching
* Leadership
* Organization
* Finance

### Research

* Scientific 
* Computational
* Security
* Market 
* Data
