---
title: "Work Experience"
---

<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
</script>

## Research & Business Development Center

### Lineage Logistics

#### Assistant Project Manager - Part Time

September 2020 - December 2020 --- Remote

* Used Python to create functions, classes, and Machine Learning algorithms
* Developed code in shortest path optimization for warehouse robot
* Recruited new members and helped members with the onboarding process
* Lead Scrum meetings and helped programmers develop code

### LLNL - Lawrence Livermore National Labs

#### Research Specialist - Intern

July 2020 - September 2020 --- Remote

* Tested security technologies using binary analysis
* Conducted market research on new security techniques
* Followed Scrum methodology and Kanban (Trello) board

## NASA - National Aeronautics and Space Administration

#### Contract

### Student Senior Designer

April 2020 – July 2020 --- Remote

* Was contracted by NASA for my Senior Project
* Worked in a 4 person team, as a team, our goal was:
  + Develop an FPGA (PolarFire) based RISC-V processor 
  + Associate software to monitor vitals in space
  + Design, Assemble, and Solder a PCB to interface with sensors  
* My contribution was: 
  + Developed embedded C interface to the sensors in NASA's Spacesuit 
  + Benchmark tested the microprocessor in C++
  + Setup the [website](https://ecen499-nasa.github.io/) using Rmds, CSS and Yaml
  
##### Mission Statement

Using the PolarFire FPGA Eval kit and a custom PCB, benchmark various RISC-V core configurations in Triple Modular Redundancy (TMR) for use in NASA’s Caution and Warning System (CWS) in the Portable Life Support System (PLSS) of the newest space suit (xEMU - Exploratory Extravehicular Mobility Unit).  

## Brigham Young University - Idaho 

#### Part Time

### Teaching Assistant {.tabset .tabset-fade}

#### C Programming 

July 2020 – Present --- Remote

* Help students learn C and C++ programming language 
* Assist the professor in creating new material

#### Intro Engineering 

January 2020 – Present --- Rexburg, ID and Remote

* Mentor new students in Engineering and Computer Science
* Help students with basic circuit analysis
* Lead students in learning arduino skills

#### Digital Systems 

September 2018 – Present --- Rexburg, ID

*	Lead students to increase their knowledge of Digital Systems
*	Guide students to improvement by giving feedback
*	Help students with programming Verilog 

#### Discrete Math

April 2019 - July 2019 --- Rexburg, ID

* Solved example problems to assist students with Discrete Math
* Assisted students in learning Elisp and Erlang

### Computer Science Tutor 

April 2018 - August 2018 --- Rexburg, ID

* Tutored many classes    
  Including:
  + Object-Oriented Programming with Data Structures using Python
  + Fundamentals of Digital Systems
  + Digital Systems Lab
  + Introduction to Engineering
  + Introduction to Electrical and Computer Engineering 
* Taught students topics from these classes
* Lead group and individual appointments and discussions