---
title: "resume"
author: Kyle Tolliver
output: 
  pagedown::html_resume:
    self_contained: true
---

<style>

.blocks {break-inside: avoid;}

p, ul {color: black;}

</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Aside
====================================

Contact Info {#contact}
------------------------------------

- <i class="fa fa-envelope"></i> [kyle@tollivers.org](mailto:kyle@tollivers.org?subject=Job)

- <i class="fa fa-phone"></i> [(805)367-6723](tel: 18053676723)

- <i class="fa fa-linkedin"></i> [linkedin.com/in/kctolli/](https://www.linkedin.com/in/kctolli/)

- <i class="fa fa-globe-americas"></i> [kctolli.github.io](../index.html)

- <i class="fa fa-github"></i> [github.com/kctolli](https://github.com/kctolli)

Skills {#skills}
------------------------------------

- R/Rmd 
- YAML
- Python
- C/C++
- Tableau
- SQL
- HTML 
- CSS
<!-- - JavaScript -->
- Java
- Verilog
- Embedded C
- Assembly
- Github

Disclaimer {#disclaimer}
------------------------------------

Member of Tau Beta Pi <br /> Engineering Honor Society <br /> Idaho Delta chapter at BYU-Idaho.

This resume was made with <br /> the R package [pagedown](https://github.com/rstudio/pagedown).

Main
====================================

Kyle Tolliver {#title}
------------------------------------

Education {data-icon=graduation-cap}
------------------------------------

### Brigham Young University - Idaho

Bachelor of Science in Software Engineering <br/> Associate of Applied Science in Data Science

Rexburg, ID

2017 <br> | <br> 2020

+ Minor: Computer Engineering
+ Societies: Data Science Society, IEEE, and ACM
+ Coursework: Machine Learning, Intermediate Stats, Data Intuition, Data Wrangling, Database Development, Software Development, Web Development, System Security, Digital System Design, Advanced Embedded Systems, Computer Architecture, Circuit Theory and Analysis, Project Management, Linear Algebra, Discrete Math, Differential Calculus  

Experience {data-icon=briefcase}
------------------------------------

### Junior Analyst

RBDC - Research and Business Development Center

Rexburg, ID

2020

+ Used Python to create classes, and Machine Learning algorithms
+ Developed code in shortest path optimization for warehouse robot
+ Lead Scrum meetings and helped programmers develop code

### Research Specialist Intern

LLNL - Lawrence Livermore National Labs

Remote

2020

+ Tested security technologies using binary analysis
+ Conducted market research on new security techniques
+ Followed Scrum methodology and Kanban (Trello) board  

### Student Senior Design Project

NASA - National Aeronautics and Space Administration

Remote

2020

+ Developed embedded C interface to the sensors in NASA's Spacesuit 
+ Benchmark tested the microprocessor in C++
+ Setup a website using Rmds, CSS and Yaml

Projects {data-icon=laptop}
------------------------------------

### COVID-19 Data Consulting

BYU - Idaho, Computer Science and Engineering 

Remote

2020

+ Developed a data website using R, Rmds and Yaml
+ Explored different datasets to determine viable information
+ Wrote my own COVID-19 R package to wrangle data
+ Visualized the data to make the data easily understood

### Biology Exam Data Analysis 		

BYU - Idaho, Computer Science and Engineering 

Rexburg, ID

2020 

*	Used R and the Tidyverse package to wrangle and visualize data
*	Allowed professors to help improve curriculum 