---
title: "CASE STUDY 11"
subtitle: "Plot 1"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
library(tidyverse)
library(buildings)
library(USAboundaries)
library(sf)
library(leaflet)

options(scipen = 999)
```

```{r continent_function}
my_continent <- function(dat){dat %>% unique() %>% filter(!state_abbr %in% c("AK","HI","PR"))}
```

```{r load_data}
# Load States
state <- my_continent(us_states()) %>% mutate(statefp = parse_number(statefp)) 
  
# Load Builds
builds <- my_continent(permits %>% 
  rename(state_abbr = "StateAbbr") %>% 
  rename(statefp = "state") %>% 
  rename(countyfp = "county") %>% 
  filter(variable == "Single Family") %>% 
  filter(year %in% c(2003, 2004, 2005, 2006, 2007, 2008)))
```

```{r create_function}
my_create <- function(state_str){
  df <- us_counties() %>% unique() %>% 
    filter(state_abbr == state_str) %>%
    mutate(countyfp = parse_number(countyfp))
  
  df
} 
```

```{r join_function}
my_join <- function(dat1, dat2){
  df <- inner_join(dat1, dat2, by = "countyfp") %>% 
    select(countyfp, countyname, year, value, geometry) %>% 
    group_by(countyfp, year) %>% 
    mutate(total = as.numeric(sum(value))) %>% 
    select(-value)
  
  df
}
```

```{r join}
USA <- inner_join(state, builds) %>% 
  select(state_abbr, year, value, geometry) %>% 
  group_by(state_abbr, year) %>% 
  mutate(total = as.numeric(sum(value))) %>% 
  select(-value)

CA <- my_join(my_create("CA"), builds)

ID <- my_join(my_create("ID"), builds)
```

```{r plot_function_CS11}
my_leaflet <- function(dat){
  pal <- colorNumeric("viridis", NULL)

  dat04 <- dat %>% filter(year == 2004)
  dat05 <- dat %>% filter(year == 2005)
  dat06 <- dat %>% filter(year == 2006)
  dat07 <- dat %>% filter(year == 2007)


  leaflet() %>% 
    addTiles() %>% 
    addPolygons(data = dat04, fillColor = ~pal(total), fillOpacity = 1, stroke = FALSE, group = "2004") %>% 
    addPolygons(data = dat05, fillColor = ~pal(total), fillOpacity = 1, stroke = FALSE, group = "2005") %>% 
    addPolygons(data = dat06, fillColor = ~pal(total), fillOpacity = 1, stroke = FALSE, group = "2006") %>%
    addPolygons(data = dat07, fillColor = ~pal(total), fillOpacity = 1, stroke = FALSE, group = "2007") %>% 
    addLayersControl(overlayGroups = c("2004", "2005", "2006", "2007"))
}
```

### USA

```{r plot_USA}
my_leaflet(USA)
```

### ID

```{r plot_ID}
my_leaflet(ID)
```

### CA

```{r plot_CA}
my_leaflet(CA)
```