---
title: "Elective Depth"
---

```{r library, include=FALSE}
library(knitr)
library(tidyverse)

setwd("D:/Portfolio/Data-Science/bac")

post_bac <- read_csv("./Post.csv")
tech <- read_csv("./Tech.csv")
```

## Applied Analysis

### General

* [ ] COMM 130 - Visual Media (3)
* [ ] POLSC 200 - Research Methods (3)
* [ ] ECON 388 - Introduction to Econometrics (3)
* [ ] MET 340 - Manufacturing Quality (3)
* [ ] SCM 361 - Operations Management (3)

### Bio-Informatics

* [ ] BIO 382 - Bioinformatics (3)
* [ ] HS 132 - Personal Health and Wellness (2)
* [ ] HS 280 - Medical Terminology (2)
* [ ] HS 310 - Environmental Health (3)
* [ ] HS 320 - Communicable and Non-Communicable Diseases (3)
* [ ] HS 370 - Epidemiology (3)
* [ ] NUTR 120 - Introduction to Dietetics (1)
* [ ] NUTR 150 - Essentials of Human Nutrition (3)

### Business

* [ ] BA 211 - Business Fundamentals (3)
* [ ] BA 215 - Spreadsheet Analysis (3)
* [ ] BA 315 - Business Analytics (3)
* [ ] BUS 100 - Business Exploration and Orientation (1)
* [X] CIT 380 - Project Management (3)
* [ ] CIT 381 - Business Intel (3)

### Finance

* [ ] ACCTG 180 - Survey of Accounting (3)
* [ ] ECON 255 - Financial Analytics (3)
* [ ] FIN 301 - Financial Management (3)
* [ ] FIN 401 - Advanced Financial Management (3)
* [ ] FIN 410 - Investments (3)
* [ ] FIN 411 - Advanced Financial Modeling (3)
* [ ] FIN 418 - Financial Planning (3)

### Marketing

* [ ] MKT 100 - Introduction to Marketing (1)
* [ ] MKT 320 - Marketing Analysis (3)
* [ ] MKT 341 - Marketing Management (3)
* [ ] MKT 352 - Digital Marketing Strategy (3)

## Programming Depth

### General

* [X] CSE 121C - C Language (1)
* [X] CSE 210 - Programming with Classes (3)
* [X] CSE 212 - Programming with Data Structures (3)
* [X] CSE 220C - C++ Language (1)
* [X] CSE 310 - Applied Programming (3)
* [ ] CSE 471 - Human Computer Interaction (3)

### Algorithms

* [ ] CSE 121a - Clojure Language (1)
* [ ] CSE 180 - Algorithmic Thinking (3)
* [ ] CSE 251 - Parallelism and Concurrency (3)
* [ ] CSE 381 - Algorithms and Complexity (3)
* [ ] CSE 480 - Computational Theory (3)

### Database

* [X] CIT 111 - Intro to Databases (3)
* [X] CIT 225 - Database Design & Development (3)
* [ ] CIT 325 - Database Programming (3)
* [ ] CIT 326 - Database Admin (3)
* [ ] CIT 327 - Data Warehousing (3)

### Design

* [ ] CSE 130 - Algorithm Design (2)
* [ ] CSE 131 - Modularization Design (2)
* [ ] CSE 232 - Designing Data Structures (2)
* [ ] CSE 270 - Software Testing (3)

### Web Development

* [ ] CIT 365 - .NET Software Development (3)
* [ ] CSE 121b - JavaScript (1)
* [ ] CSE 340 - Backend Web Development I (3)
* [ ] CSE 341 - Backend Web Development II (3)
* [ ] MKT 250 - Web Business Creation (3)
* [X] WDD 130 - Web Fundamentals (2)
* [ ] WDD 230 - Frontend Web Development I (3)
* [ ] WDD 330 - Frontend Web Development II (3)
* [ ] WDD 331 - Advanced CSS (2)
* [ ] WDD 430 - Web Full-Stack Development (3)

## Mathematics 

### General

* [X] MATH 112 - Calculus I (4)
* [ ] MATH 113 - Calculus II (3)
* [ ] MATH 119 - Data Calculus (4) 
* [ ] MATH 214 - Multivariable and Vector Calculus (3) 
* [ ] MATH 215 - Multivariable Calculus (4)
* [ ] MATH 316 - Differential Equations (4)

### Discrete and Computational 

* [X] CSE 280 - Discrete Mathematics I (2)
* [ ] CSE 380 - Discrete Mathematics II (4)
* [ ] MATH 241 - Linear Algebra Fundamentals (2)
* [X] MATH 341 - Linear Algebra (3)
* [ ] MATH 411 - Numerical Methods 1 (3)

### Applied 

* [ ] MATH 275 - Mathematics Connections (3)
* [ ] MATH 280 - Problem Solving (3)
* [ ] MATH 282 - Fundamentals of Mathematical Modeling (2)
* [ ] MATH 440 - Modern Algebra (3)
* [ ] MATH 441 - Abstract Algebra I (3)
* [ ] MATH 461 - Real Analysis I (3)

### Statistics

* [X] CSE 150 - Data Intuition and Insight (2)
* [ ] MATH 221 - Statistics (3)
* [ ] MATH 283 - Modeling Probability (2)
* [ ] MATH 325 - Intermediate Stats (3)
* [ ] MATH 326 - Experimental Design (3)
* [ ] MATH 425 - Applied Linear Regression (3)
* [ ] MATH 423 - Probability and Statistics (3)
* [ ] MATH 424 - Mathematical and Bayesian Statistics (3)
* [ ] MATH 488 - Stat Consulting (3)