---
title: "Oregon State"
output: 
  html_document:
    keep_md: true
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
```

## CS 

### MS

At least 45 hours of graduate level courses.

At least two courses each out of three areas from the following list:

* Theoretical Computer Science: CS 515-517, CS 52X
* Artificial Intelligence: CS 53X
* Computer Systems: CS 57X, CS 54X, ECE 57X
* Programming Languages: CS 58X
* Software Engineering: CS 560, CS 561, CS 562, CS 563, CS 564, CS 567, CS 569
* Human Computer Interaction: CS 564, CS 565, CS 567, CS 568, ROB 567
* Computer Vision and Graphics: CS 55X
* An area approved by the committee

--- At least a 3.0 GPA must be achieved over these six courses.

A coherent set of 3 or more courses giving preparation and support for the student’s thesis or project. The selection of courses will be made in consultation with, and must be approved by, the student’s major professor.

At least a B grade (or equivalent) in the following courses at the graduate or undergraduate level:

* Theory of Computation (equivalent of CS 321)
* Analysis of Algorithms (equivalent of CS 325)
* Operating Systems (equivalent of CS 444) 
* Computer Architecture (equivalent of CS 472)
* Translators (equivalent of CS 480) 
* Programming Languages (equivalent of CS 381)

### MEng

At least 45 credit hours of graduate-level courses approved by the student’s graduate committee.  *Please note the Graduate School requires that no more than 50% of credits are slash courses (the 5XX component of a 4XX/5XX course).

At least two courses each out of three areas from the following list:

* Theoretical Computer Science: CS 515-517, CS 52X
* Artificial Intelligence: CS 53X
* Computer Systems: CS 57X, CS 54X, ECE 57X
* Programming Languages: CS 58X
* Software Engineering: CS 560, CS 561, CS 562, CS 563, CS 564, CS 567, CS 569
* Human Computer Interaction: CS 564, CS 565, CS 567, CS 568, ROB 567
* Computer Vision and Graphics: CS 55X
* An area approved by the committee

--- At least a 3.0 GPA must be achieved over these six courses.

At least a B grade (or equivalent) in the following courses at the graduate or undergraduate level:

* Theory of Computation (equivalent of CS 321)
* Analysis of Algorithms (equivalent of CS 325)
* Operating Systems (equivalent of CS 444) 
* Computer Architecture (equivalent of CS 472)
* Translators (equivalent of CS 480) 
* Programming Languages (equivalent of CS 381)

## Data Analytics 

### MS

In Oregon State University's online Master of Science in Data Analytics program, you'll explore real data problems that are interesting and challenging as you equip yourself with the quantitative tools needed to gather, analyze and interpret data on a massive scale.

All courses in this program were developed and are taught by full-time Oregon State faculty members, and the coursework integrates OSU's strengths in statistics, computer science, mathematics, policy and applied sciences such as genomics.

#### Degree requirements

This 45-credit master's program includes a combination of courses in statistics, computer science and statistics electives. You may be able to transfer up to 15 credits into the program.

##### Prerequisites 

* ST 351:	INTRODUCTION TO STATISTICAL METHODS	

#####	Core (Stats/CS)

* ST 516:	FOUNDATIONS OF DATA ANALYTICS	
  + ST 351:	INTRODUCTION TO STATISTICAL METHODS	
* ST 517:	DATA ANALYTICS I 
  + ST 516:	FOUNDATIONS OF DATA ANALYTICS
* ST 518:	DATA ANALYTICS II
  + ST 517:	DATA ANALYTICS I 
* ST 558:	MULTIVARIATE ANALYTICS	
  + ST 518:	DATA ANALYTICS II
* ST 566:	TIME SERIES ANALYTICS	
  + ST 516:	FOUNDATIONS OF DATA ANALYTICS	
  + ST 517:	DATA ANALYTICS I 
  + ST 518:	DATA ANALYTICS II
* ST 595:	CAPSTONE PROJECT	
  + ST 516:	FOUNDATIONS OF DATA ANALYTICS	
  + ST 517:	DATA ANALYTICS I 
  + ST 518:	DATA ANALYTICS II
  + ST 558:	MULTIVARIATE ANALYTICS
* CS 511:	PROGRAMMING AND DATA STRUCTURES	
* CS 512:	DATA SCIENCE TOOLS AND PROGRAMMING
  + CS 511:	PROGRAMMING AND DATA STRUCTURES	
* CS 513:	Applied Machine Learning

##### Electives in Statistics	

Select 12 credits of the following:	

* ST 515: DESIGN AND ANALYSIS OF PLANNED EXPERIMENTS
  + ST 511: METHODS OF DATA ANALYSIS
* ST 525: APPLIED SURVIVAL ANALYSIS	
  + ST 516:	FOUNDATIONS OF DATA ANALYTICS	
  + ST 517:	DATA ANALYTICS I 
  + ST 518:	DATA ANALYTICS II
* ST 537: DATA VISUALIZATION	
  + ST 517:	DATA ANALYTICS I 
* ST 538: MODERN STATISTICAL METHODS FOR LARGE AND COMPLEX DATA SETS	
  + ST 517:	DATA ANALYTICS I 
* ST 539: SURVEY METHODS	
  + ST 351:	INTRODUCTION TO STATISTICAL METHODS
* ST 591: INTRODUCTION TO QUANTITATIVE GENOMICS	
* ST 592: STATISTICAL METHODS FOR GENOMICS RESEARCH	

### Certificate 

Examine the role statistics play in the collection and interpretation of data in Oregon State University's online Graduate Certificate in Data Analytics. You will explore real data problems that are interesting and challenging as you equip yourself with the quantitative tools needed to gather, analyze and interpret data on a massive scale.

#### Required courses

* ST 516:	FOUNDATIONS OF DATA ANALYTICS	
  + ST 351:	INTRODUCTION TO STATISTICAL METHODS	
* ST 517:	DATA ANALYTICS I 
  + ST 516:	FOUNDATIONS OF DATA ANALYTICS
* ST 518:	DATA ANALYTICS II
  + ST 517:	DATA ANALYTICS I 
* ST 558:	MULTIVARIATE ANALYTICS	
  + ST 518:	DATA ANALYTICS II
* ST 566:	TIME SERIES ANALYTICS	
  + ST 516:	FOUNDATIONS OF DATA ANALYTICS	
  + ST 517:	DATA ANALYTICS I 
  + ST 518:	DATA ANALYTICS II