#+TITLE: Grading
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+STARTUP: showeverything entitiespretty
#+SETUPFILE: ../theme-bigblow.setup

* Overview
  As stated in the syllabus, Ponder and Prove assignments are weighted at 70% of
  your final grade. These assignments consist of reading the book and working
  the exercises, problems and puzzles (EPPs) therein.

  Each ##-ponder--prove.org file will have the structure:

  1. Top-level headings for Exercises, Problems, and Puzzles
  2. Second-level headings for each three-letter acronym.

  There should ideally be about 20 exercises. The file will specify which
  problems are required (a fixed number, usually 10), the rest are optional.
* Breakdown
  For computing the grade for EPPs, there are five raw score components or
  factors:

  1. Ex for Exercises
  2. Pr for Problems
  3. Pu for Puzzles
  4. Mc for Mechanical care
  5. Tt for Time tracking

  These are explained below. The calculation for the \ldquo{}cooked\rdquo score entered into
  the gradebook is:
#+BEGIN_SRC emacs-lisp
  (* (+ (* Ex Pr) Pu Mc) Tt)
#+END_SRC

  Note that all cooked scores are normalized to 100 points possible. You will
  also note that the same score can be achieved through a variety of different
  strategies (see below).
** Exercises
    Each exercise solution is either right or wrong (1 or 0). The Ex factor is
    the number correct divided by the total number, making a number between 0.0
    and 1.0 its value.
** Problems
    All problems are weighted equally on a scale from 1-10. The Pr factor is the
    *average* of these divided by 10, so it also has a value between 0.0 and 1.0
    (but possibly more).
*** Attempt
     0-6: You made an attempt, your score is determined by how far you got.
*** Success
     7: You reached the desired output/answer by proceeding in a
     straightforward, brute-force manner --- not including just searching for
     and finding someone else\rsquo{}s answer.
*** General
     8-9: Your solution is worth more if it works for all input(s) with error
     checking and test cases.
*** Elegant
     10-15: The more elegant, the more points.
** Puzzles
    Each puzzle has four point scales (see below), which are typically presented
    following the problem definition in the ##-ponder--prove.org file. You can
    earn points for each of them *independently*, which means you do not have to
    do them *all* to get *some* points. The sum of these four components is the
    Pu factor.
*** Rephrase
     0.0 - 0.1: a textual description showing you understand the \ldquo{}heart of the
     problem\rdquo.
*** Approach
     0.0 - 0.2: a textual description of how you approached solving the problem.
*** Solution
     0.0 - 0.3: the solution itself. Points are only awarded if it works or the
     correct answer is reached.
*** Proof
     0.0 - 0.3 (or more): a textual description of how we know the solution is
     correct. The more robust the argument, the higher the points.
** Mechanical care
  This factor measures how free of *mechanical infelicities* (MIs --- e.g.,
  misspelled words, grammatical errors, punctuation errors, formatting errors)
  your writing is:

  - .0 for 4 or more MIs
  - .1 for 3 MIs
  - .2 for 2 MIs
  - .4 for 1 MI
  - .8 for 0 MIs

  Even if you are hard pressed to produce good solutions, you can always take
  steps to eliminate MIs in the solutions you do write up:

  - Spell-check and grammar-check your writing. (Have you heard of Grammarly?)
  - Read your writing aloud (or better yet, have someone else read it to you)
    to see how it sounds.
  - Have someone who is good at English carefully proofread your writing.
* Considerations
  Ignoring the Tt factor, here are some ways the same overall score can be
  achieved, for example, 90%:
  1. 100% on exercises, 90% on problems, nothing on puzzles.
  2. 90% on exercises, 100% on problems, nothing on puzzles.
  3. 90% on exercises, 90% on problems, and 9% extra credit on puzzles.

  Now, about time. You are tasked with keeping track of how long you spend on
  reading the book and doing each EPP. This should be *focused*, *concentrated*
  time --- so stop the clock before taking a break (for any reason, especially
  unexpected interruptions). Org-mode makes it easy to stop and restart timers.

  One reason for doing this time tracking is to avoid burnout. In accordance
  with the standard \ldquo{}formula\rdquo (caveat --- only for an average student seeking an
  average grade) that you should expect to spend two hours outside of class for
  every hour in, you are not *expected* to work more than 10 hours per week on
  this class. (You are also not *forbidden* to work more than that. Your
  choice.) Note that 10 hours is 8 hours in addition to the 2 you spend in
  class. That is *double* the outside-of-class hours of the above-mentioned
  standard --- the reason being that this is a more demanding course, and you
  are above-average students, or else you would not be seeking the degrees you
  are.

  Another reason for doing this tracking is that failure to do so in the
  prescribed manner will negatively impact your grade. To be explicit:

  The Tt factor is 100 minus the following:

  - 1 point for each EPP you did that you failed to track.
  - 1 point for each EPP you tracked that you failed to toggle from TODO to
    DONE.
  - 10 points for failure to include an accurate clock summary report.
